name: moniepoint_assessment_marcel
description: "Moniepoint Assessment"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animated_flip_counter: ^0.3.4
  auto_size_text: ^3.0.0
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_maps_flutter: ^2.7.0
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/json/

  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/Euclid-Circular-A-Bold-Italic.ttf
        - asset: assets/fonts/Euclid-Circular-A-Bold.ttf
        - asset: assets/fonts/Euclid-Circular-A-Italic.ttf
        - asset: assets/fonts/Euclid-Circular-A-Light-Italic.ttf
        - asset: assets/fonts/Euclid-Circular-A-Light.ttf
        - asset: assets/fonts/Euclid-Circular-A-Medium.ttf
        - asset: assets/fonts/Euclid-Circular-A-Medium-Italic.ttf
        - asset: assets/fonts/Euclid-Circular-A-Regular.ttf
        - asset: assets/fonts/Euclid-Circular-A-Semibold.ttf
        - asset: assets/fonts/Euclid-Circular-A-Semibold-Italic.ttf
